version: '3.7'

services:
  postgres-db:
    image: 'postgres:13-alpine'
    restart: always
    environment:
      - POSTGRES_USER=hr-app
      - POSTGRES_PASSWORD=hr-app
    logging:
      options:
        max-size: 10m
        max-file: "3"
    container_name: postgres-hr-app-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  hr-app:
    image: 'alidandach/hr-app:latest'
    restart: always
    build:
      context: .
    container_name: hr-app
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/hr-app
      - SPRING_DATASOURCE_USERNAME=hr-app
      - SPRING_DATASOURCE_PASSWORD=hr-app
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "9595:9595"